### ISSUE TITLE
tutorial does not work

### ISSUE THREAD

**Issue by exaexa** [SciML/SBMLToolkit.jl#14]
I'm getting 2 errors (trying on Stanford2013 model from biomodels, with fixed relational operators in SBML):

- ODEProblem constructor is missing (import it?)
- when I import it, I get this error:
```
julia> prob = ODEProblem(odesys, [], tspan, [])
ERROR: ArgumentError: Term{Real, Nothing}[s_0265(t), s_0485(t), s_1155(t), s_0557(t), s_0128(t), s_0181(t), s_1207(t), s_1415(t), s_0657(t), s_0507(t), ....................... , s_1349(t)] are missing from the variable map.
```

Any advice?

**Comment by exaexa** [comment]
(model here: https://www.ebi.ac.uk/biomodels/BIOMD0000000496)

**Comment by paulflang** [comment]
This model contains `listOfEvents` which is not supported. I created the `SBMLToolkit.checksupport(mymodel.sbml)` function to check for that in the latest release. It has to be called before readSBML(). Forgot to add it do the README. I'll update it. Thanks!

**Comment by exaexa** [comment]
there's only 1 event which seems completely unrelated to the error, that's likely far from the error cause.

**Comment by exaexa** [comment]
btw checksupport() runs okay, doesn't return any problems.

**Comment by paulflang** [comment]
are you using SBML.checksupport or SBMLToolkit.checksupport?

**Comment by exaexa** [comment]
SBMLToolkit. (there's no `SBML.checksupport`)

**Comment by paulflang** [comment]
ah, fair. anand said there was, but i've never seen it. ok, cause i get `ERROR: LoadError: SBML models with listOfEvents are not yet implemented.` locally, but i am using the dev'd version. should be the same as v0.1.2 by now. let me try using v0.1.2 tho. and also reproducing the error you get without checksupport.

**Comment by paulflang** [comment]
hmm, checksupport stills throws the same error. and when i comment it out, i get a different error than you:
```
ERROR: LoadError: DomainError with �:
Unknown SBML function
Stacktrace:
  [1] allowed_sym
    @ C:\Users\wolf5212\.julia\packages\SBML\XMU1n\src\symbolics.jl:76 [inlined]
  [2] (::SBML.var"#conv#31"{Dict{String, Any}, SBMLToolkit.var"#13#16", SBML.var"#30#35"})(x::SBML.MathApply)
    @ SBML C:\Users\wolf5212\.julia\packages\SBML\XMU1n\src\symbolics.jl:117
    ...
```
This is the code I am using:
```julia
using SBMLToolkit
using Symbolics

url = "https://www.ebi.ac.uk/biomodels/model/download/BIOMD0000000496.2?filename=BIOMD0000000496_url.xml"
tmpfile = download(url)
try
    SBMLToolkit.checksupport(tmpfile)
    ml = readSBML(tmpfile, doc -> begin
            set_level_and_version(3, 2)(doc)
            convert_simplify_math(doc)
        end)
    rs = ReactionSystem(ml)
    sys = ODESystem(ml)
finally
    rm(tmpfile)
end
```
Can you copy paste the code you are using?

**Comment by exaexa** [comment]
the same code (literally copypasted the tutorial from README). I wrote this is with the fixed relops, otherwise the model doesn't even load properly --- see https://github.com/LCSB-BioCore/SBML.jl/pull/128 .

**Comment by paulflang** [comment]
ok. that explains my `ERROR: LoadError: DomainError with �`. I'll dev SBML and see if I can reproduce your `ERROR: ArgumentError: Term{Real, Nothing}[s_0265(t), ...` now.

**Comment by exaexa** [comment]
btw the things just get merged. I think I'll release 0.6.0 to get it out asap.

**Comment by paulflang** [comment]
@exaexa : my DomainError is solved now. Is your ArgumentError solved, too or do I need to reopen this?

**Comment by exaexa** [comment]
bug persists, I fixed the DomainError before I reported this.

**Comment by paulflang** [comment]
OK. I think I have found the problem. Should be able to solve it today. In the meanwhile you can use my code example from above rather than the one from the README.

**Comment by paulflang** [comment]
@exaexa : once #16 is merged you should be able to `convert(ODESystem, rs, defaults=get_defaults(ml))` and create the ODEProblem.
